# Generated by Django 3.0.2 on 2020-02-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200201_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
